#!/bin/sh

set -e

PACKAGE=$(sed -ne '/^Package:/{s/Package:[[:space:]][[:space:]]*//p;q}' VERSION)
VERSION=$(sed -ne '/^Version:/{s/Version:[[:space:]][[:space:]]*//p;q}' VERSION)

if [ -z "$PACKAGE" ] || [ -z "$VERSION" ]; then
  echo "Error parsing package name and version from VERSION"
  exit 1
fi

echo "Tagging ${PACKAGE} version ${VERSION} as 'release/${PACKAGE}-${VERSION}'"
git tag -s "release/${PACKAGE}-${VERSION}" -m "${PACKAGE} version ${VERSION}"
